# This is a basic workflow to help you get started with Actions

name: 带中文补丁编译

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Linux 内核源码
        run: curl "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.1.131.tar.xz" -o linux.tar.xz

      - name: 解压
        run: tar xf linux.tar.xz

      - name: 改名
        run: mv linux-* linux

      - name: 下载中文补丁
        run: cd linux && curl "https://raw.githubusercontent.com/zhmars/cjktty-patches/refs/heads/master/v6.x/cjktty-6.1.patch" -o cjktty.patch

      - name: 打补丁
        run: cd linux && patch -Np1 <cjktty.patch

      - name: 安装依赖
        run: |
          sudo apt install g++
          sudo apt install bison flex libncurses-dev make libssl-dev u-boot-tools curl build-essential debhelper-compat libelf-dev

      - name: 移动配置文件
        run: cp .config linux/.config

      - name: 编译
        run: |
          cd linux
          sudo make clean
          sudo scripts/config --disable SYSTEM_REVOCATION_KEYS
          sudo scripts/config --disable SYSTEM_TRUSTED_KEYS
          sudo scripts/config --disable DEBUG_INFO
          sudo make ARCH=x86 deb-pkg -j$(nproc)

      - name: 上传文件
        uses: actions/upload-artifact@v4.6.0
        with:
          path: |
            *.deb
